### ISSUE TITLE
Scheduler support

### ISSUE THREAD

**Issue by vktor18** [logstash-plugins/logstash-input-elasticsearch#65] opened 2017-05-08 08:38 UTC
I propose to add this feature using a new parameter `schedule`

**Comment by markwalkom** [comment] 2017-05-20 22:58
++ to this. We do it for JDBC now so hopefully we can port it over easily (hopefully!).

I've also updated the topic to make the request clearer :)

**Comment by zorbalaras** [comment] 2017-07-01 16:25
+1

**Comment by okazymyrov** [comment] 2017-07-04 12:36
+1

**Comment by kabali12345** [comment] 2017-07-06 08:22
+1

**Comment by okazymyrov** [comment] 2017-07-07 06:23
The current implementation of logstash-input-elasticsearch is implemented in such a way that logstash restarts each time after completion. Scheduler has to receive a high priority since the start process of logstash is unpredictable and have lots of performance issues (e.g., https://github.com/elastic/logstash/issues/5507).

**Comment by magnusbaeck** [comment] 2017-08-02 19:28
This looks like a duplicate of #32.

**Comment by ph** [comment] 2017-08-21 19:23
closing this in favor of #32

**Closed by ph** 2017-08-21 19:23 UTC
Labels: adoptme, enhancement
