### ISSUE TITLE
Should run on a schedule

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-input-elasticsearch#88] opened 2017-12-22 22:34 UTC
This plugin should run on a schedule like the JDBC input, using cron syntax.

/cc @ctindel

**Comment by wols** [comment] 2018-01-07 22:32
I see any 'schedule forks' and I'm not deep in `rufus/scheduler` but I have been using the [logstash-input-http_poller](https://github.com/logstash-plugins/logstash-input-http_poller) for a long time.
Is it perhaps a suitable model for the schedule option?

**Comment by andrewvc** [comment] 2018-01-07 22:34
The plugin to copy would be the JDBC input in terms of scheduling options
(which I believe is quite similar).

We'd be glad to receive a patch along those lines! (With tests)

**Comment by ycombinator** [comment] 2018-01-09 21:41
Is this a duplicate of https://github.com/logstash-plugins/logstash-input-elasticsearch/issues/32?

**Comment by simianhacker** [comment] 2018-01-09 21:42
Too bad this doesn't exist... I would dog food the crap out of this and use it for all of my data collection needs.

**Comment by jsvd** [comment] 2018-01-09 21:49
btw there's already a PR that implements this https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/81/ I'll review it this week

**Comment by jsvd** [comment] 2018-01-15 14:07
implemented in #81

**Closed by jsvd** 2018-01-15 14:07 UTC
Labels: enhancement

**Comment by jsvd** [comment] 2018-01-15 15:39
support for cron-like scheduling released in version 4.2.0 👍
